In [4]:
import numpy as np
names= ['raj','anil','raj','sunil']
names=np.array(names)
data=np.arange(1,5)
data

array([1, 2, 3, 4])

In [2]:
names == 'raj'

array([ True, False,  True, False])

In [3]:
data[names=='raj']

array([1, 3])

In [7]:
data[(names=='raj') | (names=='sunil')]

array([1, 3, 4])

In [8]:
data

array([1, 2, 3, 4])

In [9]:
data.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [11]:
data.cumprod().reshape(2,2)

array([[ 1,  2],
       [ 6, 24]], dtype=int32)

In [12]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr.cumsum(axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15],
       [18, 21, 24, 27, 30],
       [34, 38, 42, 46, 50],
       [55, 60, 65, 70, 75]], dtype=int32)

In [14]:
arr.cumsum(axis=1)

array([[  1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40],
       [ 11,  23,  36,  50,  65],
       [ 16,  33,  51,  70,  90],
       [ 21,  43,  66,  90, 115]], dtype=int32)

In [15]:
arr.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325],
      dtype=int32)

In [16]:
ar1 = np.random.randn(3,3)

In [17]:
ar1

array([[-0.24890304, -2.33871671, -0.56948047],
       [-1.34225523, -0.41312676,  0.27225797],
       [ 0.54296157, -0.43112895, -0.19294596]])

In [18]:
ar1.sort()

In [19]:
ar1

array([[-2.33871671, -0.56948047, -0.24890304],
       [-1.34225523, -0.41312676,  0.27225797],
       [-0.43112895, -0.19294596,  0.54296157]])

In [21]:
ar1.sort(axis=1)
ar1

array([[-2.33871671, -0.56948047, -0.24890304],
       [-1.34225523, -0.41312676,  0.27225797],
       [-0.43112895, -0.19294596,  0.54296157]])

## Pandas
- pandas for data analysis and data manipulation(data cleanong)
- for installind pandas we can use command i.e.'pip install pandas'
- in pandas two differtent Data Structures
    - Series
    - Data Frames

In [22]:
import pandas as pd

C:\Users\Admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## Series
- it is DS
- we can use Series for generaring one dimensional array with different data types
- we have different ways for creating (or) generating Series
    - Array
    - List
    - tuples
    - dictionaries

In [23]:
import numpy as np
import pandas as pd
arr = np.arange(1,6)
s1 = pd.Series(arr)# default index for series is index=np.arange(len(arr))
s1

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [24]:
list = ['gokul','upendra','srikanth','sai']
s2=pd.Series(list)
s2

0       gokul
1     upendra
2    srikanth
3         sai
dtype: object

In [25]:
data = {'Names':['gokul','upendra','srikanth','sai'],
        'love_status':['Yes','NO','No','Yes']}

In [26]:
s3=pd.Series(data)
s3

Names          [gokul, upendra, srikanth, sai]
love_status                 [Yes, NO, No, Yes]
dtype: object

In [27]:
se = {1,2,3,4,5}
s4=pd.Series(se)
s4

TypeError: 'set' type is unordered

In [29]:
s1,s2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int32, 0       gokul
 1     upendra
 2    srikanth
 3         sai
 dtype: object)

In [30]:
# changing index posions
arr = np.arange(1,11)
ind = ['a','b','c','d','e','f','g','h','i','j']
sr = pd.Series(arr,index=ind)
sr

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

In [32]:
# Accessing Series Elements
# 1) based on element
# 2) based on index positions
sr[0]
sr['b']

2

In [34]:
sr

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

In [36]:
sr.loc['b']

2

In [39]:
sr.iloc[1]

2

In [40]:
sr.iloc[[0,2,4,6]]

a    1
c    3
e    5
g    7
dtype: int32

In [41]:
sr.loc[['b','d','e']]

b    2
d    4
e    5
dtype: int32

In [42]:
sr

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

### Series Operations

In [43]:
sr.mean()

5.5

In [44]:
sr.max()

10

In [45]:
sr.min()

1

In [46]:
sr.std()

3.0276503540974917

In [47]:
sr.var()

9.166666666666666

In [48]:
sr.head()

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [49]:
sr.head(8)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int32

In [50]:
sr.tail()

f     6
g     7
h     8
i     9
j    10
dtype: int32

In [51]:
sr.tail(3)

h     8
i     9
j    10
dtype: int32

## Attributes

In [52]:
sr.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [53]:
sr.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
sr.size

10

In [55]:
sr.itemsize

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


4

In [56]:
sr.dtype

dtype('int32')

In [58]:
s2 = pd.Series([1,2,3,4],dtype='int64')
s2

0    1
1    2
2    3
3    4
dtype: int64

In [59]:
s2.dtype

dtype('int64')

In [60]:
s2.itemsize

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


8

In [61]:
s2.T

0    1
1    2
2    3
3    4
dtype: int64