In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.mean()

3.0

In [4]:
arr1.var()

2.0

In [5]:
arr1.std()

1.4142135623730951

In [6]:
ar2 = np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar2.mean()

5.0

In [8]:
ar2.var()

6.666666666666667

In [9]:
ar2.std()

2.581988897471611

In [10]:
ar2.mean(1)

array([2., 5., 8.])

In [11]:
ar2.mean(0)

array([4., 5., 6.])

In [12]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.dot(ar2,ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
np.transpose(ar2)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
np.dot(ar2,ar2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [18]:
m1=np.arange(1,5).reshape(2,2)
m2 = np.arange(5,9).reshape(2,2)
m1,m2

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [34]:
np.concatenate((m1,m2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.concatenate((m1,m2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [36]:
np.vstack((m1,m2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.hstack((m1,m2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
m3=np.hstack((m1,m2))

In [39]:
m3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [40]:
m3.shape

(2, 4)

In [43]:
arr1.size

5

In [44]:
m3.size

8

In [45]:
arr1

array([1, 2, 3, 4, 5])

In [46]:
arr1[:]

array([1, 2, 3, 4, 5])

In [47]:
arr1[1:]

array([2, 3, 4, 5])

In [48]:
arr1[:3]

array([1, 2, 3])

In [49]:
arr1[2:5]

array([3, 4, 5])

In [50]:
m2

array([[5, 6],
       [7, 8]])

In [51]:
m3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
m= np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
m[:,1]

array([ 2,  7, 12, 17, 22])

In [54]:
m[1,:]

array([ 6,  7,  8,  9, 10])

In [55]:
m[2,2]

13

In [56]:
m[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
m[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
m[:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [59]:
m[:,-1]# all rows and last column

array([ 5, 10, 15, 20, 25])

In [60]:
# all rows and last 2 columns
m[:,-2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [61]:
# except 1st and last row
m[1:-1,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [62]:
# except 1st and last column
m[:,1:-1]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [63]:
m[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [65]:
# retrive values from m which are above 6
m[m>6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25])

In [67]:
m[m%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [68]:
np.random

<module 'numpy.random' from 'C:\\Users\\Admin\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [69]:
np.random.random()

0.12109415336420559

In [70]:
np.random.random(5)# it returns 

array([0.65466794, 0.58172878, 0.58770001, 0.98617956, 0.75145628])

In [71]:
np.random.random((2,5))

array([[0.58216815, 0.99908798, 0.78611299, 0.16706732, 0.11861339],
       [0.79186743, 0.06585549, 0.96639646, 0.14880036, 0.21658185]])