## Day Objective
 - Numpy
     - numpy stands for numaric python
     - using for scientific caluculations
     - and also for processing multidimensional array
     - this is external module so 'import numpy'
     - it is library build with c
     - for installing numpy 'pip install numpy'
     - advantages is less memory,faster

In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
l1 = [2,4,6,8,10]

In [7]:
type(l1)

list

In [8]:
l1 = np.array(l1)

In [9]:
type(l1)

numpy.ndarray

In [10]:
t1 = (1,2,3,4,5)

In [11]:
t1 = np.array(t1)

In [12]:
type(t1)

numpy.ndarray

In [13]:
li = range(1,500)
li

range(1, 500)

In [14]:
li[2]

3

In [15]:
len(li)

499

In [16]:
import sys

In [17]:
sys.getsizeof(li)

48

In [18]:
arr = np.arange(1,500)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [19]:
len(arr)

499

In [24]:
arr.itemsize

4

In [26]:
%%timeit -n 1
print('1')

1
1
1
1
1
1
1
The slowest run took 7.60 times longer than the fastest. This could mean that an intermediate result is being cached.
15.6 µs ± 16 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
import time as dt

In [41]:
dt.time()

1577694982.404814

In [42]:
li

range(1, 500)

In [61]:
import time
stime = time.time()
li=range(10000)
for i in li:
    i+=2
    #print(i+2,end=',')
etime  = time.time()
print((etime-stime)*1000)

0.0


In [62]:
arr+2

array([   2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  124,  125,  126,  127,  128,  129,  130,  131,  132,  133,
        134,  135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
        145,  146,  147,  148,  149,  150,  151,  1

In [63]:
stime = time.time()
arr = np.arange(10000)
arr+2
etime  = time.time()
print((etime-stime)*1000)

0.0


## different ways to generate arrays
- array()
- arange()
- linspace()
- logspace()
- ones()
- zeros()

In [64]:
a1 = np.array([1,2,3,4,5,6,7])

In [65]:
a1 = np.array(range(500))

In [66]:
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [73]:
a2 = np.arange(1,10)

In [74]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a3 = np.linspace(1,10)
len(a3)

50

In [77]:
a3 = np.linspace(1,10,20)
len(a3)

20

In [81]:
a2=np.arange(1,10,20)
a2

array([1])

In [82]:
np.linspace(1,50,500)

array([ 1.        ,  1.09819639,  1.19639279,  1.29458918,  1.39278557,
        1.49098196,  1.58917836,  1.68737475,  1.78557114,  1.88376754,
        1.98196393,  2.08016032,  2.17835671,  2.27655311,  2.3747495 ,
        2.47294589,  2.57114228,  2.66933868,  2.76753507,  2.86573146,
        2.96392786,  3.06212425,  3.16032064,  3.25851703,  3.35671343,
        3.45490982,  3.55310621,  3.65130261,  3.749499  ,  3.84769539,
        3.94589178,  4.04408818,  4.14228457,  4.24048096,  4.33867735,
        4.43687375,  4.53507014,  4.63326653,  4.73146293,  4.82965932,
        4.92785571,  5.0260521 ,  5.1242485 ,  5.22244489,  5.32064128,
        5.41883768,  5.51703407,  5.61523046,  5.71342685,  5.81162325,
        5.90981964,  6.00801603,  6.10621242,  6.20440882,  6.30260521,
        6.4008016 ,  6.498998  ,  6.59719439,  6.69539078,  6.79358717,
        6.89178357,  6.98997996,  7.08817635,  7.18637275,  7.28456914,
        7.38276553,  7.48096192,  7.57915832,  7.67735471,  7.77

In [83]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [84]:
np.logspace(1,10,20)

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [86]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [87]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [88]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [89]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [91]:
a1 = np.array([1,2,3,4,5.1])
a1

array([1. , 2. , 3. , 4. , 5.1])

In [92]:
a1 = np.array([1,2,3,4,5.1],dtype=int)
a1

array([1, 2, 3, 4, 5])

In [93]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [94]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [95]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21])

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [97]:
arr  = arr+2

In [98]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21])

In [99]:
arr - 2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [100]:
arr *2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42])

In [101]:
arr/2

array([ 1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,
        7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [102]:
arr//2

array([ 1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,  9,
       10, 10], dtype=int32)

In [103]:
arr**2

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225,
       256, 289, 324, 361, 400, 441], dtype=int32)

In [104]:
arr  = np.array([range(1,4),range(4,7)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
ar.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
# generate 5X5 matrix
num = np.arange(25)
num.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
arr = np.arange(1,10).reshape(3,3)

In [112]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [114]:
arr.sum()# returns sum of all eleemnts

45

In [115]:
arr.sum(1) # returns sum of each and avery row 

array([ 6, 15, 24])

In [116]:
arr.sum(0) # return sum of each and every column

array([12, 15, 18])

In [117]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
arr.max() # it returns maximum element from array

9

In [119]:
arr.max(1)

array([3, 6, 9])

In [121]:
arr.min(axis=0)

array([1, 2, 3])