In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('diabetes.csv')
x = df.drop('Outcome',axis = 1)

In [7]:
y = df.Outcome

In [10]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x,y)
y_pred = log_reg.predict(x)
from sklearn.metrics import accuracy_score,confusion_matrix,r2_score
accuracy_score(y,y_pred)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7747395833333334

In [11]:
confusion_matrix(y,y_pred)

array([[448,  52],
       [121, 147]], dtype=int64)

In [12]:
448+147

595

In [13]:
595+121+52

768

In [15]:
595/768

0.7747395833333334

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
log_reg1 = LogisticRegression()
log_reg1.fit(x_train,y_train)
y_pred = log_reg1.predict(x_test)
accuracy_score(y_test,y_pred)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.828125

In [19]:
confusion_matrix(y_test,y_pred)

array([[122,  11],
       [ 22,  37]], dtype=int64)

In [21]:
log_reg1.predict([[1,2,3,46,7,90,34,56]])

array([1], dtype=int64)

In [20]:
x.shape

(768, 8)